"""
======================================================================
UTILS ---

Some useful functions.

    Author: Zi Liang <zi1415926.liang@connect.polyu.hk>
    Copyright © 2025, ZiLiang, all rights reserved.
    Created: 17 June 2025
======================================================================
"""


# ------------------------ Code --------------------------------------
from nltk.tokenize import word_tokenize
import random

def weighted_middle_path4edit_distance(a: str, b: str) -> str:
    """
    Calculate the weighted middle edit path between two strings (word-based)

    Parameters:
        a, b: Input strings

    Returns:
        A middle string between a and b, generated by randomly weighted edit paths
    """
    # Tokenize the strings
    tokens_a = word_tokenize(a)
    tokens_b = word_tokenize(b)
    
    m, n = len(tokens_a), len(tokens_b)
    result = []
    i = j = 0

    while i < m and j < n:
        if tokens_a[i] == tokens_b[j]:
            # Keep identical words directly
            result.append(tokens_a[i])
            i += 1
            j += 1
        else:
            # Calculate weights for choosing between a's and b's word
            remaining_a = m - i
            remaining_b = n - j
            prob_a = remaining_a / (remaining_a + remaining_b)

            # Randomly select word based on weights
            if random.random() < prob_a:
                result.append(tokens_a[i])
                i += 1
            else:
                result.append(tokens_b[j])
                j += 1

    # Append remaining words
    result.extend(tokens_a[i:] if i < m else tokens_b[j:])

    # Join tokens into string with simple punctuation handling
    return ' '.join(result).replace(' .', '.').replace(' ,', ',')

def split_text_by_word_counts(text_list, step=5):
    result = []
    
    for text in text_list:
        words = text.split() 
        max_length = len(words)
        
        for n in range(step, max_length + 1, step):
            truncated_text = ' '.join(words[:n])
            result.append(truncated_text)
            
        if max_length % step != 0:
            result.append(' '.join(words))
    
    return result
